// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrARNMxauEq8g8BXkRfSwsDLoff3LGvgU',
    appId: '1:889621432902:web:5e167751453ad8189f5847',
    messagingSenderId: '889621432902',
    projectId: 'ditonton-4081b',
    authDomain: 'ditonton-4081b.firebaseapp.com',
    storageBucket: 'ditonton-4081b.appspot.com',
    measurementId: 'G-P9FH17GXJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JQ8EVlzY_6BplIFcFlclmk_urpaP40A',
    appId: '1:889621432902:android:fdd513fa75d1df589f5847',
    messagingSenderId: '889621432902',
    projectId: 'ditonton-4081b',
    storageBucket: 'ditonton-4081b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc8kKfbgcjYT5u93oDrcteRpKUFoC33FE',
    appId: '1:889621432902:ios:076c2d030b83d9019f5847',
    messagingSenderId: '889621432902',
    projectId: 'ditonton-4081b',
    storageBucket: 'ditonton-4081b.appspot.com',
    iosClientId: '889621432902-lhf152ohn5r39pdsqueosb39de22tqde.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
